name: Flutter Workflow

# This workflow is triggered on pushes to the repository.

on:
  push:
    branches:
    - master
    - bugfix
    
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    - run: flutter build apk --debug --split-per-abi
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*"
        tag: v1.0.${{github.run_number}}
        token: ${{secrets.BECHDAL}}
    

   
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v3
      with:
        name: debug-apk
        path: build/app/outputs/apk/release/app-release.apk
